name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
core: 8.x
hidden: true
install:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2020-09-16
version: '8.9.6'
project: 'drupal'
datestamp: 1600276320
